version: "3.9"
services:
  postgres:
    container_name: ${DB_CONTAINER}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_PORT: ${DB_CONTAINER_PORT}
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - "db_container"

volumes:
  dbdata: 