
-- Users
DROP TABLE users CASCADE;
DROP DOMAIN IF EXISTS gender CASCADE; 
DROP DOMAIN IF EXISTS phone_number CASCADE;
DROP DOMAIN IF EXISTS email CASCADE;


-- Address
DROP TABLE address CASCADE;
DROP DOMAIN IF EXISTS pincode CASCADE;
DROP DOMAIN IF EXISTS phone_number_address CASCADE;